config/routes.rb
Family::Application.routes.draw do
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations',
    passwords:      'users/passwords',
    confirmations:  'users/confirmations'
  }

  mount ElVfsClient::Engine => '/'

  namespace :manage do
    resources :children
    get 'adult_children' => 'children#adult'
    root :to => 'children#index'
    resources :contest_works

    resources :social_providers, :only => [:index, :show, :destroy] do
      post 'publish', :on => :member
      post 'draft',   :on => :member
    end
  end

  get 'ru/children' => 'children#index', :as => :children
  get 'ru/children/view' => 'children#show', :as => :child

  get 'ru/departament/uchebno-metodicheskiy-tsentr/request' => 'requests#new', :as => :new_request
  post 'ru/departament/uchebno-metodicheskiy-tsentr/request' => 'requests#create', :as => :create_request

  get 'ru/dream-picture' => 'contest_works#index'

  resources :social_providers, :only => [:index, :show], :path => '/ru/na-povestke-dnya/reestr-postavschikov-sotsialnyh-uslug'

  namespace :my do
    resources :social_providers do
      post 'pending', :on => :member
    end
  end

  resources :contest_works, :only => [:index] do
    resources :contest_votes, :only => [:create]
  end

  get '/(*path)' => 'application#index'
end

app/models/request.rb
# encoding: utf-8

class Request < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone

  validates_presence_of :name, :email, :message
  validates_format_of :name, :with => /\A([ёЁа-яА-Я]+\s*)+\z/
  validates :email, :email_format => { :message => I18n.t('activerecord.errors.messages.invalid') }
end

# == Schema Information
#
# Table name: requests
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  phone      :string(255)
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/requests_controller.rb
#encoding: utf-8

class RequestsController < MainController
  def new
    @request = Request.new(params[:request])

    super
  end

  def create
    super

    @request = Request.new(params[:request])

    if verify_recaptcha(:model => @request) && @request.save
      redirect_to new_request_path, :notice => 'Сообщение отправлено успешно, спасибо за обращение.'
    else
      @request.valid?

      render :new
    end
  end
end

app/views/requests/new.html.erb
<%= content_for :content do %>
  <%= content_tag :div, render(:partial => 'regions/right_side'), :class => 'right_side' if @right_side_navigation || @right_side_links || @right_side_charts || @right_side_facts %>
  <%= @content_first.content.body %>

    <div class='request'>
      <div class='flash_message'>
        <%= flash[:notice] %>
        <%= flash[:recaptcha_error].nil? ? '' : t('recaptcha.errors.verification_failed') %>
      </div>

      <%= simple_form_for @request, :url => create_request_path, :html => {:novalidate => true} do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :phone %>
        <%= f.input :message %>
        <div class='recaptcha'>
          <%= recaptcha_tags :display => {:theme => 'white'}, :ajax => true %>
        </div>
        <div class='submit'>
          <%= f.submit "Отправить" %>
        </div>
      <% end %>

    </div>
<% end %>