config/routes.rb
Family::Application.routes.draw do
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations',
    passwords:      'users/passwords',
    confirmations:  'users/confirmations'
  }

  mount ElVfsClient::Engine => '/'

  namespace :manage do
    resources :children
    get 'adult_children' => 'children#adult'
    root :to => 'children#index'
    resources :contest_works

    resources :social_providers, :only => [:index, :show, :destroy] do
      post 'publish', :on => :member
      post 'draft',   :on => :member
    end
  end

  get 'ru/children' => 'children#index', :as => :children
  get 'ru/children/view' => 'children#show', :as => :child

  get 'ru/departament/uchebno-metodicheskiy-tsentr/request' => 'requests#new', :as => :new_request
  post 'ru/departament/uchebno-metodicheskiy-tsentr/request' => 'requests#create', :as => :create_request

  get 'ru/dream-picture' => 'contest_works#index'

  resources :social_providers, :only => [:index, :show], :path => '/ru/na-povestke-dnya/reestr-postavschikov-sotsialnyh-uslug'

  namespace :my do
    resources :social_providers do
      post 'pending', :on => :member
    end
  end

  resources :contest_works, :only => [:index] do
    resources :contest_votes, :only => [:create]
  end

  get '/(*path)' => 'application#index'
end

app/models/social_provider.rb
class SocialProvider < ActiveRecord::Base
  attr_accessible :additional_info, :address, :audits, :chief_fio, :incorporation_form, :site,
                  :register_date, :short_title, :terms_of_service, :title, :work_experience,
                  :phones_attributes, :emails_attributes, :licenses_attributes,
                  :social_forms_attributes, :social_services_attributes,
                  :revert_to_draft_reason

  belongs_to :user

  has_many :phones,          :order => 'created_at', :dependent => :destroy
  has_many :emails,          :order => 'created_at', :dependent => :destroy
  has_many :licenses,        :order => 'created_at', :dependent => :destroy
  has_many :social_forms,    :order => 'created_at', :dependent => :destroy
  has_many :social_services, :order => 'created_at', :dependent => :destroy

  accepts_nested_attributes_for :phones, :emails, :licenses, :social_forms, :social_services, :allow_destroy => true

  validates_presence_of :title, :short_title, :register_date, :address, :chief_fio

  scope :not_draft, -> { where(:state => [:pending, :published]) }
  scope :published, ->(_) { where(:state => :published) }
  scope :by_update, -> { order('updated_at desc') }

  state_machine :initial => :draft do
    event :pending do
      transition :draft => :pending
    end

    event :publish do
      transition :pending => :published
    end

    event :draft do
      transition [:pending, :published] => :draft
    end
  end

  def places_full_number
    self.social_forms.map(&:places_number).compact.sum
  end

  def free_places_full_number
    self.social_forms.map(&:free_places_number).compact.sum
  end
end

# == Schema Information
#
# Table name: social_providers
#
#  id                     :integer          not null, primary key
#  title                  :text
#  short_title            :text
#  register_date          :date
#  incorporation_form     :text
#  address                :text
#  chief_fio              :text
#  terms_of_service       :text
#  audits                 :text
#  work_experience        :text
#  additional_info        :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :integer
#  site                   :string(255)
#  state                  :string(255)
#  revert_to_draft_reason :text
#

app/controllers/my/social_providers_controller.rb
class My::SocialProvidersController < ApplicationController
  include Pundit

  before_filter :user_not_authorized, :unless => 'current_user.present?'

  def index
    @social_providers = policy_scope(SocialProvider)
  end


  def show
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider, :manage?
  end

  def new
    @social_provider = current_user.social_providers.new
    authorize @social_provider, :manage?
  end

  def create
    @social_provider = current_user.social_providers.new(params[:social_provider])
    authorize @social_provider, :manage?

    if @social_provider.save
      redirect_to my_social_provider_path(@social_provider)
    else
      render :new
    end
  end

  def edit
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider
  end

  def update
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider, :edit?
    if @social_provider.update_attributes(params[:social_provider])
      redirect_to my_social_provider_path(@social_provider)
    else
      render :edit
    end
  end

  def destroy
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider

    @social_provider.destroy
    redirect_to my_social_providers_path
  end

  def pending
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider, :to_pending?

    updated_at = @social_provider.updated_at
    @social_provider.pending!
    @social_provider.update_column :updated_at, updated_at
    redirect_to my_social_providers_path
  end

  private

  def user_not_authorized
    flash[:alert] = "Необходимо произвести вход в систему"
    redirect_to social_providers_path
  end
end

app/controllers/social_providers_controller.rb
class SocialProvidersController < MainController
  inherit_resources

  has_scope :published, :default => 1

  actions :index, :show

  def index
    index!{ @social_providers = @social_providers.page(params[:page] || 1).per(20) }
  end
end

app/views/social_providers/_social_provider.html.erb
<li>
  <%= link_to social_provider.short_title, social_provider_path(social_provider) %>
</li>

app/views/social_providers/index.html.erb
<% content_for :content do %>

  <%= content_tag :div, render(:partial => 'regions/right_side'), :class => 'right_side' if @right_side_navigation || @right_side_links || @right_side_charts || @right_side_facts %>

  <div class="article">
    <%= render_partial_for_region(@content_first)  if @content_first %>

    <%= render :partial => 'flash', :locals => { :flash => flash } %>

    <p>
      <% if current_user %>
        Вы вошли как:
        <%= current_user.email %>
        |
        <%= link_to 'Анкеты поставщика социальных услуг', my_social_providers_path %>
        |
        <%= link_to 'Выход', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Вход в систему', new_user_session_path %>
        |
        <%= link_to 'Регистрация', new_user_registration_path %>
        |
        <%= link_to 'Забыли пароль?', new_user_password_path %>
      <% end %>
    </p>

    <p>Федеральный закон Российской Федерации от 28 декабря 2013 г. N 442-ФЗ <a href='http://www.rg.ru/2013/12/30/socialka-dok.html' target='_blank'>«Об основах социального обслуживания граждан в Российской Федерации»</a></p>

    <div class="social_providers list">
      <ul>
        <%= render @social_providers %>
      </ul>
      <%= paginate @social_providers %>
    </div>

    <%= render_partial_for_region(@content_second) if @content_second %>
    <%= render_partial_for_region(@content_third)  if @content_third %>
    <%= render :partial => 'regions/reports_part', :locals => { :reports => @reports } if @reports %>
    <%= yield :social_links %>
  </div>
<% end %>

app/views/social_providers/show.html.erb
<% content_for :social_provider_links do %>
  <%= link_to 'вернуться к списку', social_providers_path %>
<% end %>

<% content_for :content do %>
  <h2><%= @social_provider.short_title %></h2>
  <%= render :partial => 'commons/social_providers/show' %>
<% end %>