config/routes.rb
Family::Application.routes.draw do
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations',
    passwords:      'users/passwords',
    confirmations:  'users/confirmations'
  }

  mount ElVfsClient::Engine => '/'

  namespace :manage do
    resources :children
    get 'adult_children' => 'children#adult'
    root :to => 'children#index'
    resources :contest_works

    resources :social_providers, :only => [:index, :show, :destroy] do
      post 'publish', :on => :member
      post 'draft',   :on => :member
    end
  end

  get 'ru/children' => 'children#index', :as => :children
  get 'ru/children/view' => 'children#show', :as => :child

  get 'ru/departament/uchebno-metodicheskiy-tsentr/request' => 'requests#new', :as => :new_request
  post 'ru/departament/uchebno-metodicheskiy-tsentr/request' => 'requests#create', :as => :create_request

  get 'ru/dream-picture' => 'contest_works#index'

  resources :social_providers, :only => [:index, :show], :path => '/ru/na-povestke-dnya/reestr-postavschikov-sotsialnyh-uslug'

  namespace :my do
    resources :social_providers do
      post 'pending', :on => :member
    end
  end

  resources :contest_works, :only => [:index] do
    resources :contest_votes, :only => [:create]
  end

  get '/(*path)' => 'application#index'
end

app/models/social_provider.rb
class SocialProvider < ActiveRecord::Base
  attr_accessible :additional_info, :address, :audits, :chief_fio, :incorporation_form, :site,
                  :register_date, :short_title, :terms_of_service, :title, :work_experience,
                  :phones_attributes, :emails_attributes, :licenses_attributes,
                  :social_forms_attributes, :social_services_attributes,
                  :revert_to_draft_reason

  belongs_to :user

  has_many :phones,          :order => 'created_at', :dependent => :destroy
  has_many :emails,          :order => 'created_at', :dependent => :destroy
  has_many :licenses,        :order => 'created_at', :dependent => :destroy
  has_many :social_forms,    :order => 'created_at', :dependent => :destroy
  has_many :social_services, :order => 'created_at', :dependent => :destroy

  accepts_nested_attributes_for :phones, :emails, :licenses, :social_forms, :social_services, :allow_destroy => true

  validates_presence_of :title, :short_title, :register_date, :address, :chief_fio

  scope :not_draft, -> { where(:state => [:pending, :published]) }
  scope :published, ->(_) { where(:state => :published) }
  scope :by_update, -> { order('updated_at desc') }

  state_machine :initial => :draft do
    event :pending do
      transition :draft => :pending
    end

    event :publish do
      transition :pending => :published
    end

    event :draft do
      transition [:pending, :published] => :draft
    end
  end

  def places_full_number
    self.social_forms.map(&:places_number).compact.sum
  end

  def free_places_full_number
    self.social_forms.map(&:free_places_number).compact.sum
  end
end

# == Schema Information
#
# Table name: social_providers
#
#  id                     :integer          not null, primary key
#  title                  :text
#  short_title            :text
#  register_date          :date
#  incorporation_form     :text
#  address                :text
#  chief_fio              :text
#  terms_of_service       :text
#  audits                 :text
#  work_experience        :text
#  additional_info        :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :integer
#  site                   :string(255)
#  state                  :string(255)
#  revert_to_draft_reason :text
#

app/controllers/my/social_providers_controller.rb
class My::SocialProvidersController < ApplicationController
  include Pundit

  before_filter :user_not_authorized, :unless => 'current_user.present?'

  def index
    @social_providers = policy_scope(SocialProvider)
  end


  def show
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider, :manage?
  end

  def new
    @social_provider = current_user.social_providers.new
    authorize @social_provider, :manage?
  end

  def create
    @social_provider = current_user.social_providers.new(params[:social_provider])
    authorize @social_provider, :manage?

    if @social_provider.save
      redirect_to my_social_provider_path(@social_provider)
    else
      render :new
    end
  end

  def edit
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider
  end

  def update
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider, :edit?
    if @social_provider.update_attributes(params[:social_provider])
      redirect_to my_social_provider_path(@social_provider)
    else
      render :edit
    end
  end

  def destroy
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider

    @social_provider.destroy
    redirect_to my_social_providers_path
  end

  def pending
    @social_provider = SocialProvider.find(params[:id])
    authorize @social_provider, :to_pending?

    updated_at = @social_provider.updated_at
    @social_provider.pending!
    @social_provider.update_column :updated_at, updated_at
    redirect_to my_social_providers_path
  end

  private

  def user_not_authorized
    flash[:alert] = "Необходимо произвести вход в систему"
    redirect_to social_providers_path
  end
end

app/controllers/social_providers_controller.rb
class SocialProvidersController < MainController
  inherit_resources

  has_scope :published, :default => 1

  actions :index, :show

  def index
    index!{ @social_providers = @social_providers.page(params[:page] || 1).per(20) }
  end
end

app/views/my/social_providers/_email_fields.html.erb
<%= f.input :value %>
<%= f.link_to_remove 'Удалить' %>

app/views/my/social_providers/_form.html.erb
<div class='attention'>
  Внимание! Периодически сохраняйте информацию для избежания потери вводимых данных!
</div>

<%= simple_nested_form_for [:my, @social_provider] do |f| %>
  <%= f.input :title %>
  <%= f.input :short_title %>
  <%= f.input :register_date, :as => :datepicker %>
  <%= f.input :incorporation_form %>
  <%= f.input :chief_fio %>
  <%= f.input :address %>
  <%= f.input :site %>

  <fieldset class='phones'>
    <legend>Телефоны</legend>
    <%= f.simple_fields_for :phones %>
    <%= f.link_to_add 'Добавить телефон', :phones %>
  </fieldset>

  <fieldset class='emails'>
    <legend>Адреса электронной почты</legend>
    <%= f.simple_fields_for :emails %>
    <%= f.link_to_add 'Добавить адрес электронной почты', :emails %>
  </fieldset>

  <%= f.input :terms_of_service %>
  <%= f.input :audits %>
  <%= f.input :work_experience %>
  <%= f.input :additional_info %>

  <fieldset class='licenses'>
    <legend>Информация о лицензиях</legend>
    <%= f.simple_fields_for :licenses %>
    <%= f.link_to_add 'Добавить информацию о лицензии', :licenses %>
  </fieldset>

  <fieldset class='social_forms'>
    <legend>Формы социального обслуживания</legend>
    <%= f.simple_fields_for :social_forms %>
    <%= f.link_to_add 'Добавить форму социального обслуживания', :social_forms %>
  </fieldset>

  <fieldset class='social_services'>
    <legend>Социальные услуги</legend>
    <%= f.simple_fields_for :social_services %>
    <%= f.link_to_add 'Добавить социальную услугу', :social_services %>
  </fieldset>

  <div class='actions'>
    <%= f.submit 'Сохранить', :class => 'button' %>
    <% if f.object.new_record? %>
      <%= link_to 'Отмена', my_social_providers_path, :class => 'button' %>
    <% else %>
      <%= link_to 'Отмена', my_social_provider_path(f.object), :class => 'button' %>
    <% end %>
  </div>
<% end %>

app/views/my/social_providers/_license_fields.html.erb
<%= f.input :seria %>
<%= f.input :number %>
<%= f.input :issue_date, :as => :datepicker %>
<%= f.input :expiration_date, :as => :datepicker, :placeholder => 'оставьте пустым, если лицензия бессрочна' %>
<%= f.link_to_remove 'Удалить' %>
<%= f.input :activity_kind %>
<%= f.input :issuing_organization %>

app/views/my/social_providers/_links.html.erb
<%= link_to 'редактировать', edit_my_social_provider_path(social_provider) if policy(social_provider).edit? %>
<% if social_provider.draft? %>
  <%= link_to 'отправить на публикацию', pending_my_social_provider_path(social_provider), :method => :post if policy(social_provider).to_pending? %>
<% elsif social_provider.pending? %>
  <span>(возможность именения заблокирована)</span>
<% end %>
<%= link_to 'удалить', my_social_provider_path(social_provider), :method => :delete, :confirm => 'Вы уверены что хотите удалить?' if policy(social_provider).destroy? %>

app/views/my/social_providers/_phone_fields.html.erb
<%= f.input :kind, :as => :select %>
<%= f.input :value %>
<%= f.link_to_remove 'Удалить' %>

app/views/my/social_providers/_social_form_fields.html.erb
<%= f.input :kind, :as => :select %>
<%= f.input :places_number %>
<%= f.input :free_places_number %>
<%= f.link_to_remove 'Удалить' %>

app/views/my/social_providers/_social_provider.html.erb
<li>
  <%= link_to social_provider.short_title, my_social_provider_path(social_provider) %>
  <span class='social_provider_state <%= social_provider.state %>'><%= social_provider.human_state_name %></span>
  <span class='social_provider_last_update'>Изменено: <%= I18n.l social_provider.updated_at %></span>
</li>

app/views/my/social_providers/_social_service_fields.html.erb
<%= f.input :kind, :as => :select %>
<%= f.input :title %>
<%= f.input :price %>
<%= f.link_to_remove 'Удалить' %>

app/views/my/social_providers/edit.html.erb
<% content_for :content do %>
  <h1>Редактирование информации о поставщике социальных услуг</h1>
  <%= render :partial => 'form' %>
<% end %>

app/views/my/social_providers/index.html.erb
<% content_for :content do %>
  <h1>Мой реестр</h1>

  <p>
    <% if current_user %>
      Вы вошли как:
      <%= current_user.email %>
      |
      Анкеты поставщика социальных услуг
      |
      <%= link_to 'Выход', destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to 'Вход в систему', new_user_session_path %>
      |
      <%= link_to 'Регистрация', new_user_registration_path %>
      |
      <%= link_to 'Забыли пароль?', new_user_password_path %>
    <% end %>
  </p>

  <p>Федеральный закон Российской Федерации от 28 декабря 2013 г. N 442-ФЗ <a href='http://www.rg.ru/2013/12/30/socialka-dok.html' target='_blank'>«Об основах социального обслуживания граждан в Российской Федерации»</a></p>

  <p><%= link_to 'Добавить информацию о поставщике социальных услуг', new_my_social_provider_path %></p>

  <div class='social_providers list'>
    <ul>
      <%= render @social_providers %>
    </ul>
  </div>
<% end %>

app/views/my/social_providers/new.html.erb
<% content_for :content do %>
  <h1>Добавление информации о поставщике социальных услуг</h1>
  <%= render :partial => 'form' %>
<% end %>

app/views/my/social_providers/show.html.erb
<% content_for :social_provider_links do %>
  <span class='social_provider_state small <%= @social_provider.state %>'><%= @social_provider.human_state_name %></span>
  <span class='social_provider_last_update without_margin'>Изменено: <%= I18n.l @social_provider.updated_at %></span>
  <%= render :partial => 'links', :locals => { :social_provider => @social_provider } %>
  <%= link_to 'вернуться к списку', my_social_providers_path %>
<% end %>

<% content_for :content do %>
  <h1><%= @social_provider.short_title %></h1>
  <%= render :partial => 'commons/social_providers/show' %>
<% end %>